### ISSUE TITLE
Attention: Please do something to prevent password leaked

### ISSUE THREAD

**Issue by lsvih** [lukevictor/apemesp#1]
Olá, I read a article about cipher leaks today, and tried searching some keyword at github. Then I found this repo, please do something as soon to protect your database and account.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/5164225/33552522-1e2c6f94-d930-11e7-906f-105087077b09.png">

**Comment by lukevictor** [comment]
Hey man, thanks for the issue. I inserted the file on the gitignore and changed the password of the database.
